#!/bin/bash

#$ -S /bin/bash
#$ -N mpi_dida
#$ -l mem_token=45G,mem_free=45G,h_vmem=45G,excl=true
#$ -R y
#$ -q mpi.q
#$ -pe openmpi 6
#$ -o $JOB_ID.o
#$ -e $JOB_ID.e

export PATH=/home/hmohamadi/gcc-4.9.1/bin/:/home/hmohamadi/dida_mpi/bin/:/home/hmohamadi/openmpi-1.6.5/bin/:/home/hmohamadi/abyss-1.5.2/bin/:$PATH
export LIBRARY_PATH=/home/hmohamadi/openmpi-1.6.5/lib:/home/hmohamadi/gcc-4.9.1/lib64/:/home/hmohamadi/gcc-4.9.1/lib/:$LIBRARY_PATH
export LD_LIBRARY_PATH=/home/hmohamadi/openmpi-1.6.5/lib:/home/hmohamadi/gcc-4.9.1/lib64/:/home/hmohamadi/gcc-4.9.1/lib/:$LD_LIBRARY_PATH

export mpirun='mpirun --mca btl_openib_receive_queues X,128,256,192,128:X,4096,256,128,32:X,12288,256,128,32:X,65536,256,128,3'
echo mpirun="$mpirun"
which mpirun

echo "==> pe_hostfile <=="
cat $PE_HOSTFILE
echo

echo "Job started at: $(date)"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

mpirun -np 6 dida -p4 -b28 chr14.in /scratch/hmohamadi/dida_mpi_test/chr/ABySSTest-3.fa 

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Job ended at:   $(date)"
