#!/bin/bash

#$ -S /bin/bash

#$ -l mem_token=46G,mem_free=46G,h_vmem=46G,excl=true
#$ -q mpi.q,all.q
#$ -o /scratch/hmohamadi/DIDA/src_mpi/$JOB_ID.o
#$ -e /scratch/hmohamadi/DIDA/src_mpi/$JOB_ID.e
#$ -j y

echo "==> pe_hostfile <=="
cat $PE_HOSTFILE
echo

export OMP_NUM_THREADS=12
/scratch/hmohamadi/DIDA/bin/bfl_omp ABySSTest-3.fa 28 12 /scratch/hmohamadi/partition/chr14/treads.fastq
